### ISSUE TITLE
Easily close connection

### ISSUE THREAD

**Issue by rugk** [onyxbits/remotekeyboard#21]
It would be nice if the notification of the RK app would include a button "Close connection" or better "Stop Remote Keyboard", which would then disable the keyboard and choose another one.

This would make it more convenient to use. :smiley:

**Comment by onyxbits** [comment]
There is a "close connection" button on the "keyboard" (the one with the flash). Switching to another keyboard from within RK is not possible. Android won't allow that (for security reasons, only the the user may switch keyboards and may only do so from the system settings apps).
