### ISSUE TITLE
Local echo of only last few char(s)

### ISSUE THREAD

**Issue by rugk** [onyxbits/remotekeyboard#22]
I read https://github.com/onyxbits/remotekeyboard/issues/2, but what about this idea:
Only show the last char or let's say 3-5 chars entered, also show backspace as `⬸` (or similar - if you cannot see it I mean :arrow_left:) e.g.

This would avoid all problems mentioned in #2  and at least provide some feedback on PC.
Passwords are also no problem to show as 1) users should be aware that telnet is insecure anyway, so they should not enter any passwords in the first place, 2) also Android has an option to show the last character of an entered password, so this would behave very similar.

**Comment by onyxbits** [comment]
Believe me, I tried making local echo work. It doesn't. And it is not needed anyways. Just move your eyes from your big to your little screen ;).
