### ISSUE TITLE
Use on lockscreen

### ISSUE THREAD

**Issue by rugk** [onyxbits/remotekeyboard#23]
I noticed I cannot use RK to wake up my device from standby and I also cannot use it from the lock screen to enter PIN/Password.

Although I - for security reason - think that the latter is okay, the former would be a useful feature, but if it might have a bad effect on the battery, it should be optional.
And even the PIN input could be implemented. I mean it is the user's responsibility to only use this is a secure WLAN.

**Comment by onyxbits** [comment]
> I noticed I cannot use RK to wake up my device from standby and I also cannot use it from the lock screen to enter PIN/Password.

When your system is in standby, your radio is turned off. So there is no way to wake up your device via network. I haven't checked on the PIN thing, but I wouldn't be surprised if Android mandates that you can only use the system keyboard for that.

**Comment by rugk** [comment]
> Android mandates that you can only use the system keyboard for that.

At least I know you can also use a hardware keyboard.
