### ISSUE TITLE
Cannot switch from one Startscreen to another

### ISSUE THREAD

**Issue by rugk** [onyxbits/remotekeyboard#24]
I can navigate from one startscreen panel to the other one. I can navigate from one startscreen icon to another one, but it always stops at the end of the screen.

With a hardware keyboard I can do this, so this seems to be possible. 

CM 13

**Comment by onyxbits** [comment]
I'm afraid, I don't have CM13 at hand, so I can't check this one

**Comment by rugk** [comment]
Could you still please leave this issue open for others to check?
