### ISSUE TITLE
security issues wrt telnet?

### ISSUE THREAD

**Issue by landroni** [onyxbits/remotekeyboard#4]
I'm no security expert, but I vaguely remember reading that installing a telnet client on a Linux system represents a serious security issue. Are there potential security issues when installing remotekeyboard on Android? 

Thanks!

**Comment by ypid** [comment]
@chvostek Great idea. I wrote a script for that: https://github.com/ypid/scripts/blob/master/remotekeyboard-login

It sets up a ssh Port forwording, connects via telnet and enters the password …
Maybe it will be useful for somebody.
